sudo: required
dist: trusty

language: cpp

env:
  - C_COMPILER=gcc-7 CXX_COMPILER=g++-7
  - C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0

before_install:
  - pyenv global system 3.6
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-5.0 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install gcc-7 g++-7 -y
  - sudo apt-get install clang-5.0 -y
  - sudo apt-get install libboost-all-dev libopencv-dev -y
  - wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz
  - tar -xvzf cmake-3.8.2-Linux-x86_64.tar.gz

before_script:
  - mkdir build
  - cd build
  - ../cmake-3.8.2-Linux-x86_64/bin/cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DEOS_BUILD_EXAMPLES=on -DEOS_BUILD_UTILS=on -DEOS_GENERATE_PYTHON_BINDINGS=on -DPYTHON_EXECUTABLE=`which python3.6` ..

script:
  - make VERBOSE=1
